apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qhkz9438p-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qhkz9438p-nodejs 
  name: qhkz9438p-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qhkz9438p-nodejs 
